version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=${DATABASE_NAME:-admin}
      - POSTGRES_USER=${DATABASE_USER:-admin}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD:-mysecretpassword}
    ports:
      - 5432:5432

  db-test:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=${DATABASE_NAME:-admin}
      - POSTGRES_USER=${DATABASE_USER:-admin}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD:-mysecretpassword}
    ports:
      - 5431:5432

  server:
    image: boto/server:demo-1.0
    build:
      context: ./server
    depends_on:
      - db
    environment:
      - SECRET=${SECRET}
      - DATABASE_NAME=${DATABASE_NAME:-admin}
      - DATABASE_USER=${DATABASE_USER:-admin}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD:-mysecretpassword}
      - DATABASE_HOST=db
      - DATABASE_PORT=${DATABASE_PORT:-5432}
      - FLASK_ENV=${FLASK_ENV:-DEVELOPMENT}
    ports:
      - "5000:5000"

  webapp:
    image: boto/webapp:demo-1.0
    build:
      context: ./webapp
    environment:
      - VITE_API_URL=${VITE_API_URL:-http://localhost:5000}
      - VITE_VISUALIZER_URL=${VITE_VISUALIZER_URL:-http://localhost:5006}
    ports:
      - "4173:4173"

  admin:
    image: boto/admin:demo-1.0
    build:
      context: ./admin
    environment:
      - VITE_API_URL=${VITE_API_URL:-http://localhost:5000}
    ports:
      - "4172:4173"

  webviz:
    image: boto/webviz:demo-1.0
    build:
      context: ./seismic-webviz
    environment:
      - FLASK_ENV=${FLASK_ENV:-DEVELOPMENT}
      - API_URL=${API_URL:-http://host.docker.internal:5000}
    volumes:
      - ./server/static:/home/jorb/code/CloudSeis/server/static
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "5006:5006"
