version: '3.1'

services:

  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: mysecretpassword

  server:
    build: ./server
    ports:
      - "8000:5000"

  webapp:
    build: ./webapp
    ports:
      - "5173:5173"