version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_NAME=${DATABASE_NAME:-admin}
      - POSTGRES_USER=${DATABASE_USER:-admin}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD:-mysecretpassword}
    ports:
      - 5432:5432

  db-test:
    image: postgres
    restart: always
    environment:
      - POSTGRES_NAME=${DATABASE_NAME:-admin}
      - POSTGRES_USER=${DATABASE_USER:-admin}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD:-mysecretpassword}
    ports:
      - 5431:5432

  server:
    build: ./server
    depends_on:
      - db
    environment:
      - SECRET=${SECRET}
      - DATABASE_NAME=${DATABASE_NAME:-admin}
      - DATABASE_USER=${DATABASE_USER:-admin}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD:-mysecretpassword}
      - DATABASE_HOST=db
      - DATABASE_PORT=${DATABASE_PORT:-5432}
      - FLASK_ENV=${FLASK_ENV:-DEVELOPMENT}
    ports:
      - "5000:5000"

  webapp:
    build: ./webapp
    ports:
      - "5173:5173"
