FROM python:3.11
WORKDIR /home/server

ENV FLASK_APP=app.create_app:create_app
ENV FLASK_RUN_HOST=0.0.0.0

RUN echo | bash -c "$(wget -qO- https://gist.githubusercontent.com/botoseis/4ca681cb9ef706c1b8410153c6199cf2/raw/b16ad754839d1ca3657d8e8396db14f5ba791e6b/install_seismic_unix.sh)"

COPY scripts/wait-for-it.sh /usr/local/bin/wait-for-it.sh
RUN chmod +x /usr/local/bin/wait-for-it.sh

COPY . .
RUN pip install -r requirements.txt
RUN chmod +x ./scripts/container_start.sh

EXPOSE 5000
CMD ["./scripts/container_start.sh"]
