"""delete_owner_email_column_at_workflow_parents_association_table

Revision ID: 0aacc9dd4365
Revises: 53c8ed7600c1
Create Date: 2025-05-12 19:36:14.029997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0aacc9dd4365'
down_revision = '53c8ed7600c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflow_parents_association_table', schema=None) as batch_op:
        batch_op.drop_constraint('FK_users_table_workflows_table', type_='foreignkey')
        batch_op.drop_column('owner_email')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflow_parents_association_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_email', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('FK_users_table_workflows_table', 'users_table', ['owner_email'], ['email'])

    # ### end Alembic commands ###
