"""create-parameters-table

Revision ID: 107447bd0def
Revises: b74c2f7fede6
Create Date: 2024-02-03 12:48:40.785698

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '107447bd0def'
down_revision = 'b74c2f7fede6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parameters_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('input_type', sa.String(), nullable=True),
    sa.Column('programId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['programId'], ['programs_table.id'], name='FK_programs_table_parameters_table'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('parameters_table')
    # ### end Alembic commands ###
