"""first-postgres-migration

Revision ID: 176c12daa1b7
Revises: 
Create Date: 2023-08-24 17:51:36.451321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '176c12daa1b7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_table',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('userId', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['users_table.id'], name='FK_users_table_projects_table'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lines_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('projectId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['projectId'], ['projects_table.id'], name='FK_projects_table_lines_table'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workflows_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('file_name', sa.String(), nullable=True),
    sa.Column('lineId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['lineId'], ['lines_table.id'], name='FK_lines_table_workflows_table'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('commands_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('parameters', sa.Text(), nullable=True),
    sa.Column('workflowId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['workflowId'], ['workflows_table.id'], name='FK_workflows_table_commands_table'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ordered_commands_list_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workflowId', sa.Integer(), nullable=True),
    sa.Column('commandIds', sa.ARRAY(sa.Integer()), nullable=True),
    sa.ForeignKeyConstraint(['workflowId'], ['workflows_table.id'], name='FK_workflows_table_workflow_commands_list_table'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ordered_commands_list_table')
    op.drop_table('commands_table')
    op.drop_table('workflows_table')
    op.drop_table('lines_table')
    op.drop_table('projects_table')
    op.drop_table('users_table')
    # ### end Alembic commands ###
