"""add-owner_email-to-multiple-tables

Revision ID: 25edbd0d6c0a
Revises: c63dc0503ed6
Create Date: 2024-03-19 03:17:31.269286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25edbd0d6c0a'
down_revision = 'c63dc0503ed6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('commands_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_email', sa.String(), nullable=True))
        batch_op.create_foreign_key('FK_users_table_commands_table', 'users_table', ['owner_email'], ['email'])

    with op.batch_alter_table('lines_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_email', sa.String(), nullable=True))
        batch_op.create_foreign_key('FK_users_table_lines_table', 'users_table', ['owner_email'], ['email'])

    with op.batch_alter_table('workflows_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_email', sa.String(), nullable=True))
        batch_op.create_foreign_key('FK_users_table_workflows_table', 'users_table', ['owner_email'], ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflows_table', schema=None) as batch_op:
        batch_op.drop_constraint('FK_users_table_workflows_table', type_='foreignkey')
        batch_op.drop_column('owner_email')

    with op.batch_alter_table('lines_table', schema=None) as batch_op:
        batch_op.drop_constraint('FK_users_table_lines_table', type_='foreignkey')
        batch_op.drop_column('owner_email')

    with op.batch_alter_table('commands_table', schema=None) as batch_op:
        batch_op.drop_constraint('FK_users_table_commands_table', type_='foreignkey')
        batch_op.drop_column('owner_email')

    # ### end Alembic commands ###
