"""switches projectId table to workflowId table in dataset model

Revision ID: 273699a80d9a
Revises: d4e8ab820aff
Create Date: 2024-07-04 14:21:46.463701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '273699a80d9a'
down_revision = 'd4e8ab820aff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('datasets_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('workflowId', sa.Integer(), nullable=True))
        batch_op.drop_constraint('FK_projects_datasets', type_='foreignkey')
        batch_op.create_foreign_key('FK_workflows_tables_datasets_table', 'workflows_table', ['workflowId'], ['id'])
        batch_op.drop_column('projectId')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('datasets_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('projectId', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint('FK_workflows_tables_datasets_table', type_='foreignkey')
        batch_op.create_foreign_key('FK_projects_datasets', 'projects_table', ['projectId'], ['id'])
        batch_op.drop_column('workflowId')

    # ### end Alembic commands ###
