"""change-workflow_parents_association_table-keys

Revision ID: 299400bf385b
Revises: 4dab71e7f3ef
Create Date: 2023-11-03 17:05:14.080770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '299400bf385b'
down_revision = '4dab71e7f3ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflow_parents_association_table', schema=None) as batch_op:
        batch_op.drop_constraint('FK_workflow_parents_association_table_projects_table', type_='foreignkey')
        batch_op.drop_constraint('FK_workflow_parents_association_table_lines_table', type_='foreignkey')
        batch_op.create_foreign_key('FK_workflow_parents_association_table_projects_table', 'projects_table', ['projectId'], ['id'])
        batch_op.create_foreign_key('FK_workflow_parents_association_table_lines_table', 'lines_table', ['lineId'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflow_parents_association_table', schema=None) as batch_op:
        batch_op.drop_constraint('FK_workflow_parents_association_table_lines_table', type_='foreignkey')
        batch_op.drop_constraint('FK_workflow_parents_association_table_projects_table', type_='foreignkey')
        batch_op.create_foreign_key('FK_workflow_parents_association_table_lines_table', 'projects_table', ['lineId'], ['id'])
        batch_op.create_foreign_key('FK_workflow_parents_association_table_projects_table', 'lines_table', ['projectId'], ['id'])

    # ### end Alembic commands ###
