"""add-owner-email-to-workflow_parents_association_table

Revision ID: 37df3075fab6
Revises: 50d15438b140
Create Date: 2024-04-22 16:50:43.464185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37df3075fab6'
down_revision = '50d15438b140'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflow_parents_association_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_email', sa.String(), nullable=True))
        batch_op.create_foreign_key('FK_users_table_workflows_table', 'users_table', ['owner_email'], ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflow_parents_association_table', schema=None) as batch_op:
        batch_op.drop_constraint('FK_users_table_workflows_table', type_='foreignkey')
        batch_op.drop_column('owner_email')

    # ### end Alembic commands ###
