"""add_owner_email_to_datasetmodel

Revision ID: 3dd4eb1f7f04
Revises: 37df3075fab6
Create Date: 2024-04-24 22:05:57.378184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3dd4eb1f7f04'
down_revision = '37df3075fab6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('datasets_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_email', sa.String(), nullable=True))
        batch_op.create_foreign_key('FK_users_table_dataset_table', 'users_table', ['owner_email'], ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('datasets_table', schema=None) as batch_op:
        batch_op.drop_constraint('FK_users_table_dataset_table', type_='foreignkey')
        batch_op.drop_column('owner_email')

    # ### end Alembic commands ###
