"""empty message

Revision ID: 416dfc18b3d9
Revises: 299400bf385b
Create Date: 2024-01-01 22:10:10.717575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '416dfc18b3d9'
down_revision = '299400bf385b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('datasets_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('projectId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['projectId'], ['datasets_table.id'], name='FK_projects_datasets'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workflow_parents_association_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('datasetId', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('FK_workflow_parents_association_table_dataset_table', 'datasets_table', ['datasetId'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflow_parents_association_table', schema=None) as batch_op:
        batch_op.drop_constraint('FK_workflow_parents_association_table_dataset_table', type_='foreignkey')
        batch_op.drop_column('datasetId')

    op.drop_table('datasets_table')
    # ### end Alembic commands ###
