"""add-output_name-column-to-workflows_table

Revision ID: 42225ebf670a
Revises: 9dba7985d438
Create Date: 2024-08-21 08:54:33.760017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42225ebf670a'
down_revision = '9dba7985d438'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflows_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('output_name', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflows_table', schema=None) as batch_op:
        batch_op.drop_column('output_name')

    # ### end Alembic commands ###
