"""hash_table_unique_to_false

Revision ID: 50d15438b140
Revises: 6843a1be0f7e
Create Date: 2024-04-18 09:57:43.206782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50d15438b140'
down_revision = '6843a1be0f7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_table', schema=None) as batch_op:
        batch_op.drop_constraint('users_table_hashPassword_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_table', schema=None) as batch_op:
        batch_op.create_unique_constraint('users_table_hashPassword_key', ['hashPassword'])

    # ### end Alembic commands ###
