"""rename_workflowId_column_to_originWorkflowId_at_datasets_table

Revision ID: 53b86c685b71
Revises: 0aacc9dd4365
Create Date: 2025-05-12 20:40:48.489564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53b86c685b71'
down_revision = '0aacc9dd4365'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('datasets_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('originWorkflowId', sa.Integer(), nullable=True))
        batch_op.drop_constraint('FK_workflows_tables_datasets_table', type_='foreignkey')
        batch_op.create_foreign_key('FK_workflows_tables_datasets_table', 'workflows_table', ['originWorkflowId'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('workflowId')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('datasets_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('workflowId', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint('FK_workflows_tables_datasets_table', type_='foreignkey')
        batch_op.create_foreign_key('FK_workflows_tables_datasets_table', 'workflows_table', ['workflowId'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('originWorkflowId')

    # ### end Alembic commands ###
