"""add-is_active-column-at-commands_table

Revision ID: 53c8ed7600c1
Revises: ac0523093ab2
Create Date: 2025-02-12 08:09:45.941095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53c8ed7600c1'
down_revision = 'ac0523093ab2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('commands_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('commands_table', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
