"""hash_column_for_user_password

Revision ID: 6843a1be0f7e
Revises: ac213ec76952
Create Date: 2024-04-08 14:31:31.919736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6843a1be0f7e'
down_revision = 'ac213ec76952'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('datasets_table', schema=None) as batch_op:
        batch_op.drop_constraint('FK_users_table_dataset_table', type_='foreignkey')
        batch_op.drop_column('owner_email')

    with op.batch_alter_table('users_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hashPassword', sa.LargeBinary(), nullable=True))
        batch_op.create_unique_constraint(None, ['hashPassword'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_table', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('hashPassword')

    with op.batch_alter_table('datasets_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_email', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('FK_users_table_dataset_table', 'users_table', ['owner_email'], ['email'])

    # ### end Alembic commands ###
