"""rename_file_link_id_column_to_input_file_link_id_at_workflows_table

Revision ID: 6bae45a14526
Revises: 53b86c685b71
Create Date: 2025-05-12 22:06:51.345659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bae45a14526'
down_revision = '53b86c685b71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflows_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('input_file_link_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('FK_file_links_table_workflows_table', type_='foreignkey')
        batch_op.create_foreign_key('FK_file_links_table_workflows_table', 'file_link_table', ['input_file_link_id'], ['id'])
        batch_op.drop_column('file_link_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflows_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_link_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint('FK_file_links_table_workflows_table', type_='foreignkey')
        batch_op.create_foreign_key('FK_file_links_table_workflows_table', 'file_link_table', ['file_link_id'], ['id'])
        batch_op.drop_column('input_file_link_id')

    # ### end Alembic commands ###
