"""feat parent id and type to workflow model attributes

Revision ID: 7c11533db05a
Revises: 273699a80d9a
Create Date: 2024-07-09 16:31:00.365623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c11533db05a'
down_revision = '273699a80d9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflows_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parentId', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('parentType', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflows_table', schema=None) as batch_op:
        batch_op.drop_column('parentType')
        batch_op.drop_column('parentId')

    # ### end Alembic commands ###
