"""add example attribute to parameter model

Revision ID: 7c8cbc206505
Revises: 9dba7985d438
Create Date: 2024-12-22 18:15:21.148919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c8cbc206505'
down_revision = '9dba7985d438'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parameters_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('example', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parameters_table', schema=None) as batch_op:
        batch_op.drop_column('example')

    # ### end Alembic commands ###
