"""create relations

Revision ID: 84923c394272
Revises: c717199e4542
Create Date: 2023-08-09 03:47:26.137917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84923c394272'
down_revision = 'c717199e4542'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seismic_commands_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seismicCommandId', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('FK_seismic_workflows_table_seismic_commands_table', 'seismic_workflows_table', ['seismicCommandId'], ['id'])

    with op.batch_alter_table('seismic_lines_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seismicProjectId', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('FK_seismic_projects_table_seismic_lines_table', 'seismic_projects_table', ['seismicProjectId'], ['id'])

    with op.batch_alter_table('seismic_projects_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('userId', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('FK_users_table_seismic_projects_table', 'users_table', ['userId'], ['id'])

    with op.batch_alter_table('seismic_workflows_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seismicLineId', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('FK_seismic_lines_table_seismic_workflows_table', 'seismic_lines_table', ['seismicLineId'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seismic_workflows_table', schema=None) as batch_op:
        batch_op.drop_constraint('FK_seismic_lines_table_seismic_workflows_table', type_='foreignkey')
        batch_op.drop_column('seismicLineId')

    with op.batch_alter_table('seismic_projects_table', schema=None) as batch_op:
        batch_op.drop_constraint('FK_users_table_seismic_projects_table', type_='foreignkey')
        batch_op.drop_column('userId')

    with op.batch_alter_table('seismic_lines_table', schema=None) as batch_op:
        batch_op.drop_constraint('FK_seismic_projects_table_seismic_lines_table', type_='foreignkey')
        batch_op.drop_column('seismicProjectId')

    with op.batch_alter_table('seismic_commands_table', schema=None) as batch_op:
        batch_op.drop_constraint('FK_seismic_workflows_table_seismic_commands_table', type_='foreignkey')
        batch_op.drop_column('seismicCommandId')

    # ### end Alembic commands ###
