"""change-workflows_table-file_name-to-file_link_id

Revision ID: a8fe9e953e92
Revises: 00ec602e1b6b
Create Date: 2024-07-29 20:48:46.705751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8fe9e953e92'
down_revision = '00ec602e1b6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflows_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_link_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('FK_file_links_table_workflows_table', 'file_link_table', ['file_link_id'], ['id'])
        batch_op.drop_column('file_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflows_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_name', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_constraint('FK_file_links_table_workflows_table', type_='foreignkey')
        batch_op.drop_column('file_link_id')

    # ### end Alembic commands ###
