"""rename_name_column_to_path_at_file_link_table

Revision ID: b29530f97483
Revises: 6bae45a14526
Create Date: 2025-06-06 02:56:54.976626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b29530f97483'
down_revision = '6bae45a14526'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file_link_table', schema=None) as batch_op:
        batch_op.alter_column('name', new_column_name='path')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file_link_table', schema=None) as batch_op:
        batch_op.alter_column('path', new_column_name='name')

    # ### end Alembic commands ###
