"""users-table-update-id

Revision ID: d225264fcb11
Revises: 84923c394272
Create Date: 2023-08-11 17:34:15.466129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd225264fcb11'
down_revision = '84923c394272'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seismic_projects_table', schema=None) as batch_op:
        batch_op.alter_column('userId',
               existing_type=sa.INTEGER(),
               type_=sa.Uuid(),
               existing_nullable=True)

    with op.batch_alter_table('users_table', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               type_=sa.Uuid(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_table', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.Uuid(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('seismic_projects_table', schema=None) as batch_op:
        batch_op.alter_column('userId',
               existing_type=sa.Uuid(),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
