"""add-isRequired-column-to-parameters_table

Revision ID: df2a8cb830f8
Revises: f6a172e23b13
Create Date: 2024-02-21 17:08:30.816290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df2a8cb830f8'
down_revision = 'f6a172e23b13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parameters_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('isRequired', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parameters_table', schema=None) as batch_op:
        batch_op.drop_column('isRequired')

    # ### end Alembic commands ###
