"""empty message

Revision ID: e9d07dae4981
Revises: 6af3c8159317
Create Date: 2024-01-24 01:00:47.483652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9d07dae4981'
down_revision = '6af3c8159317'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('datasets_table', schema=None) as batch_op:
        batch_op.drop_column('currentSate')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('datasets_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('currentSate', sa.VARCHAR(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
