"""Add-ON-DELETE-CASCADE-to-many-FKs

Revision ID: ee9f4d1f825b
Revises: 42225ebf670a
Create Date: 2024-08-27 18:23:26.656408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee9f4d1f825b'
down_revision = '42225ebf670a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('commands_table', schema=None) as batch_op:
        batch_op.drop_constraint('FK_workflows_table_commands_table', type_='foreignkey')
        batch_op.create_foreign_key('FK_workflows_table_commands_table', 'workflows_table', ['workflowId'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('datasets_table', schema=None) as batch_op:
        batch_op.drop_constraint('FK_workflows_tables_datasets_table', type_='foreignkey')
        batch_op.create_foreign_key('FK_workflows_tables_datasets_table', 'workflows_table', ['workflowId'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('file_link_table', schema=None) as batch_op:
        batch_op.drop_constraint('FK_datasets_table_file_link_table', type_='foreignkey')
        batch_op.drop_constraint('FK_projects_table_file_link_table', type_='foreignkey')
        batch_op.create_foreign_key('FK_projects_table_file_link_table', 'projects_table', ['projectId'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('FK_datasets_table_file_link_table', 'datasets_table', ['datasetId'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('ordered_commands_list_table', schema=None) as batch_op:
        batch_op.drop_constraint('FK_workflows_table_workflow_commands_list_table', type_='foreignkey')
        batch_op.create_foreign_key('FK_workflows_table_workflow_commands_list_table', 'workflows_table', ['workflowId'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('projects_table', schema=None) as batch_op:
        batch_op.drop_constraint('FK_users_table_projects_table', type_='foreignkey')
        batch_op.create_foreign_key('FK_users_table_projects_table', 'users_table', ['userId'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('workflow_parents_association_table', schema=None) as batch_op:
        batch_op.drop_constraint('FK_workflow_parents_association_table_projects_table', type_='foreignkey')
        batch_op.drop_constraint('FK_workflow_parents_association_table_workflows_table', type_='foreignkey')
        batch_op.drop_constraint('FK_workflow_parents_association_table_dataset_table', type_='foreignkey')
        batch_op.drop_constraint('FK_workflow_parents_association_table_lines_table', type_='foreignkey')
        batch_op.create_foreign_key('FK_workflow_parents_association_table_lines_table', 'lines_table', ['lineId'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('FK_workflow_parents_association_table_projects_table', 'projects_table', ['projectId'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('FK_workflow_parents_association_table_workflows_table', 'workflows_table', ['workflowId'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('FK_workflow_parents_association_table_dataset_table', 'datasets_table', ['datasetId'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflow_parents_association_table', schema=None) as batch_op:
        batch_op.drop_constraint('FK_workflow_parents_association_table_dataset_table', type_='foreignkey')
        batch_op.drop_constraint('FK_workflow_parents_association_table_workflows_table', type_='foreignkey')
        batch_op.drop_constraint('FK_workflow_parents_association_table_projects_table', type_='foreignkey')
        batch_op.drop_constraint('FK_workflow_parents_association_table_lines_table', type_='foreignkey')
        batch_op.create_foreign_key('FK_workflow_parents_association_table_lines_table', 'lines_table', ['lineId'], ['id'])
        batch_op.create_foreign_key('FK_workflow_parents_association_table_dataset_table', 'datasets_table', ['datasetId'], ['id'])
        batch_op.create_foreign_key('FK_workflow_parents_association_table_workflows_table', 'workflows_table', ['workflowId'], ['id'])
        batch_op.create_foreign_key('FK_workflow_parents_association_table_projects_table', 'projects_table', ['projectId'], ['id'])

    with op.batch_alter_table('projects_table', schema=None) as batch_op:
        batch_op.drop_constraint('FK_users_table_projects_table', type_='foreignkey')
        batch_op.create_foreign_key('FK_users_table_projects_table', 'users_table', ['userId'], ['id'])

    with op.batch_alter_table('ordered_commands_list_table', schema=None) as batch_op:
        batch_op.drop_constraint('FK_workflows_table_workflow_commands_list_table', type_='foreignkey')
        batch_op.create_foreign_key('FK_workflows_table_workflow_commands_list_table', 'workflows_table', ['workflowId'], ['id'])

    with op.batch_alter_table('file_link_table', schema=None) as batch_op:
        batch_op.drop_constraint('FK_datasets_table_file_link_table', type_='foreignkey')
        batch_op.drop_constraint('FK_projects_table_file_link_table', type_='foreignkey')
        batch_op.create_foreign_key('FK_projects_table_file_link_table', 'projects_table', ['projectId'], ['id'])
        batch_op.create_foreign_key('FK_datasets_table_file_link_table', 'datasets_table', ['datasetId'], ['id'])

    with op.batch_alter_table('datasets_table', schema=None) as batch_op:
        batch_op.drop_constraint('FK_workflows_tables_datasets_table', type_='foreignkey')
        batch_op.create_foreign_key('FK_workflows_tables_datasets_table', 'workflows_table', ['workflowId'], ['id'])

    with op.batch_alter_table('commands_table', schema=None) as batch_op:
        batch_op.drop_constraint('FK_workflows_table_commands_table', type_='foreignkey')
        batch_op.create_foreign_key('FK_workflows_table_commands_table', 'workflows_table', ['workflowId'], ['id'])

    # ### end Alembic commands ###
