"""update-programs_table-add-relation-to-program_groups_table

Revision ID: f6a172e23b13
Revises: adee4a67ead6
Create Date: 2024-02-06 18:18:10.991614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6a172e23b13'
down_revision = 'adee4a67ead6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('programs_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('groupId', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('FK_program_groups_table_programs_table', 'program_groups_table', ['groupId'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('programs_table', schema=None) as batch_op:
        batch_op.drop_constraint('FK_program_groups_table_programs_table', type_='foreignkey')
        batch_op.drop_column('groupId')

    # ### end Alembic commands ###
