name: Run Tests
on:
  push:
    branches:
      - master
    paths:
      - 'server/**'
      - '.github/workflows/tests.yml'
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize
    branches:
      - master
    paths:
      - 'server/**'
      - 'workspace/**'
      - 'Makefile'
      - 'docker-compose.yml'
  workflow_dispatch: {}

jobs:

  tests:
    name: Test server
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: Install dependecies
      run: pip install -r server/requirements.txt

    - name: Make
      run: make test

    - name: run tests
      run: cd server/ && pytest
